motherduck integration test improvements (#777)
While investigating why MotherDuck integration tests have been taking over 45 minutes, found that one of the microbatch tests left behind many temporary tables that kept accumulating. 

This PR fixes the issue on 2 levels: 
* fix the faulty temp table cleanup mechanism for incremental microbatch models when hitting a compilation error:  the post-model-hook cleanup omitted the batch's batch_id when computing the temp relation path, so it looked for the wrong table name and missed the orphaned temp table left behind by the failed batch. 
* All motherduck tests now use a new database name generated per test session- besides preventing the original issue, this also allows mutliple concurrent test runs to not step on each other. 


Also reverted "Bump pyarrow from 24.0.0 to 25.0.0 (#781)" to fix segfaults introduced to motherduck integration tests from the upgrade

---------

Co-authored-by: Josh Wills <josh.wills@gmail.com>